### ISSUE TITLE
[Spike] Pose estimation investigation

### ISSUE THREAD

**Issue by jherrmann06** [frc1675/frc1675-2024-general#5]
Prereq: frc1675/frc1675-2024#8 
Action: Determine what our pose estimation goals are and communicate with programming team
Success criteria: Issues created for all pose estimation goals

**Comment by Bholoubek** [comment]
there is an unofficial limelight crescendo map for April tags locations.   Last year in February, limelight had an official release with full map for the settings

**Comment by jherrmann06** [comment]
frc1675/frc1675-2024#27
