### ISSUE TITLE
[Spike] Github actions (CI/CD)

### ISSUE THREAD

**Issue by jagernet-ops** [frc1675/frc1675-2024-general#8]
Prereq: None
Action: Research/ produce code sample demonstrating the use of GitHub actions to check build status and any other useful functions.
Success criteria: Issues are created which correspond to the teams goals for CI/CD

**Comment by jagernet-ops** [comment]
Resources:
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

**Comment by shinysocks** [comment]
ooh, yay! I'll work on this saturday

**Comment by pordonj** [comment]
What I would like to see by next Saturday (1/20)

Build a robot project repository using github actions
Run any unit test from a robot project using github actions (this can even be asserting that 2+2 = 4)
Write a small guild on what you need to set it up on any robot repository

**Comment by jherrmann06** [comment]
Nobody was working on this so I just went ahead and did it. 

- [x] frc1675/frc1675-2024#19
