### ISSUE TITLE
[Spike] Quality Control & Versioning

### ISSUE THREAD

**Issue by jherrmann06** [frc1675/frc1675-2024-general#9]
Prereq: None
Action: Research / produce code samples demonstrating how we can use the build script or other compile time features to capture information about the current version of the code (think branch name, commit information, other git info)
Success criteria: Effective versioning strategy is identified, related issues are created to guide further work

**Comment by jherrmann06** [comment]
~~Resources: 
https://github.com/ajoberstar/reckon
https://github.com/ajoberstar/grgit
https://stackoverflow.com/questions/41368957/how-to-write-gradle-build-currentversion-to-a-file~~

**Comment by python-42** [comment]
https://github.com/TripleHelixProgramming/HelixUtilities/wiki/HelixLogger

**Comment by jherrmann06** [comment]
See frc1675/frc1675-2024#4 and frc1675/frc1675-2024#3
